name: 'Prettify Pester Reports'
author: 'de-taylor-scb'
description: 'Prettify Pester Reports is a GitHub Action designed to convert the XML outputs from the Pester Unit Testing framework into Markdown for easy display in GitHub PR comments or other locations that support Markdown formatting.'
branding:
  icon: 'code'
  color: 'blue'
inputs:
  path:
    description: 'The path string that points to the XML file you want to parse. Must be parseable by pathlib.Path()'
    required: true
  output:
    description: 'The path string that points to the location where you want the Markdown file to be written. Must be parseable by pathlib.Path()'
    required: true
  reportType:
    description: 'The type of report that this script is parsing. Each type has restricted schema options.'
    required: true
  reportSchema:
    description: 'The specific XML schema that will be used to parse this XML report. Each report type has restricted schema options.'
    required: true
  headingLevel:
    description: 'The topmost heading that should be included in the report. e.g. 1 for H1 (#), 2 for H2 (##), and so on. All other headings will be placed relative to the top level. Defaults to 3 (###).'
    required: false
    default: '3'
  minLineCov:
    description: 'The minimum coverage threshold for line coverage, between 0.0 and 100.0'
    required: false
    default: '0.0'
  minInstructionCov:
    description: 'The minimum coverage threshold for instruction coverage, between 0.0 and 100.0'
    required: false
    default: '0.0'
  minMethodCov:
    description: 'The minimum coverage threshold for method coverage, between 0.0 and 100.0'
    required: false
    default: '0.0'
  minClassCov:
    description: 'The minimum coverage threshold for class coverage, between 0.0 and 100.0'
    required: false
    default: '0.0'
runs:
  using: 'composite'
  steps:
    - name: Set up Python 3.13.0 environment
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'
        cache: 'pip' # cache pip dependencies for use later
    - name: Get pip dependencies
      shell: pwsh
      run: pip install
    - name: Run Prettify Pester Reports
      shell: pwsh
      run: |
        # set the script path using the github.action_path
        $scriptPath = Join-Path "${{ github.action_path }}" "main.py"
        
        py $scriptPath --xml_path ${{ inputs.path }} --output_path ${{ inputs.output }} --report_type ${{ inputs.reportType }} --report_schema ${{ inputs.reportSchema }} --heading_level ${{ inputs.headingLevel }} --min_line_cov ${{ inputs.minLineCov }} --min_instr_cov ${{ inputs.minInstructionCov }} --min_method_cov $${{ inputs.minMethodCov }} --min_class_cov $${{ inputs.minClassCov }}