"""The Prettify Pester Reports Action was created to build Markdown formatted reports from the XML files generated by the Pester Unit Testing framework.

At present, this Action supports the following report types, and has limited support for formats for each type:

 - `testResult` (default `testResults.xml`): 'NUnit3'
 - `coverage` (default `coverage.xml`): 'JaCoCo'

As interest or need arises, other code coverage types will be supported.

Future Supported Schemas by Report Type:
 - `testResult`: 'NUnitXML', 'NUnit2.5', 'JUnitXml'
 - `coverage`: 'CoverageGutters', 'Cobertura'

Raises:
    UserWarning: Raised if the functions don't generate any Markdown, which may indicate an issue with the processing function used.

Returns:
    int: Returns an exit code that corresponds to the number of errors encountered during processing.
"""
# Python 3 Standard Library Imports
from pathlib import Path
import sys
import xml.etree.ElementTree as ET

# Custom Module Imports
from src.utilities import create_md_file, validate_args, parse_args

if __name__ == '__main__':
    # removed arg parsing to its own function, pass in all args other than file name
    args = parse_args(sys.argv[1:])

    args_valid, args_errors = validate_args(args)

    if args_valid:
        # XML input file is now proven to exist, call the driver function for the Markdown conversion
        try:
            cov_thresholds = {
                "line": args.min_line_cov,
                "instr": args.min_instr_cov,
                "method": args.min_method_cov,
                "class": args.min_class_cov
            }

            create_md_file(
                ET.parse(args.xml_path), # type: ignore
                Path(args.output_path),
                args.report_type,
                args.report_schema,
                cov_thresholds,
                args.heading_level
            )
        except ValueError as err:
            args_errors.append(str(err))

    # write out the errors to console
    for error in args_errors:
        print(error)
    
    sys.exit(len(args_errors)) # exit with how many errors happened