name: Python Validation

on:
    pull_request_target:
        types: [opened, synchronize, reopened]

jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Check Out Repository
              uses: actions/checkout@v6.0.1
            - name: Set up Python 3.13.0 Environment
              uses: actions/setup-python@v6.1.0
              with:
                python-version: 3.13.0
            - name: Install Dependencies
              shell: pwsh
              run: |
                python -m pip install --upgrade pip 
                pip install flake8 pytest
                # gather the defined pip requirements
                if (Test-Path -Path requirements.txt -PathType Leaf) {
                    pip install -r requirements.txt
                }
            - name: Lint with flake8
              shell: pwsh
              run: |
                # stop the build if there are Python syntac errors or bad names
                flake 8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                # treat all errors as warnings through exit 0
                flake 8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
            - name: Test with PyTest
              shell: pwsh
              run: |
                # need to figure out how to get these results into badges
                pytest -vv -cov=src --cov-report=html --cov-branch